[package]
name = "cargo-tally"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"
publish = false

[lib]
path = "src/hidden.rs"

[dependencies]
abomonation = "0.7"
atty = "0.2"
anyhow = "1.0"
bytesize = "1.0"
chrono = "0.4"
clap = "2.33"
db-dump = "0.3"
differential-dataflow = { version = "0.12", default-features = false }
num_cpus = "1.0"
once_cell = "1.8"
opener = "0.5"
ref-cast = "1.0"
regex = "1.5"
semver = "1.0"
sysinfo = { version = "0.18", default-features = false }
termcolor = "1.1"
timely = { version = "0.12", default-features = false }
typed-arena = "2.0"
